apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: github-cicd-demo
    app.kubernetes.io/instance: github-cicd-demo-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: github-cicd-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-cicd-demo
  template:
    metadata:
      labels:
        app: github-cicd-demo
    spec:
      containers:
        - image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
          imagePullPolicy: Always
          name: cicddemo
          ports:
            - containerPort: 4000
