apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: github-cicd-demo
    app.kubernetes.io/instance: github-cicd-demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: github-cicd-demo
spec:
  selector:
    app: github-cicd-demo
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 4000
      targetPort: 4000
